In [1]:
#Call Selenium

In [2]:
import requests as req
from bs4 import BeautifulSoup as bs
import pandas as pd
import json
import time 
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import warnings   # para quitar warnings
warnings.simplefilter('ignore')

#driver configuration
opciones=Options()

opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
opciones.add_experimental_option('useAutomationExtension', False)
opciones.headless=False    # si True, no aperece la ventana (headless=no visible)
opciones.add_argument('--start-maximized')         # comienza maximizado
#opciones.add_argument('user-data-dir=selenium')    # mantiene las cookies
#opciones.add_extension('driver_folder/adblock.crx')       # adblocker
opciones.add_argument('--incognito')

driver = "./chromedriver.exe"
driver = webdriver.Chrome(driver,options = opciones)

# With time.sleep()

In [3]:
############
#Start (Germany)
############
#url = 'http://www.gobiernodecanarias.org/istac/jaxi-istac/menu.do?uripub=urn:uuid:a19805e5-1674-4efd-b047-1ab0abac9c36'
#driver.get(url)
#
#print('Progress 0%')
#print('Working on Germany....')    
##Getting data on imports
#
#time.sleep(3)
#
#imports=driver.find_element_by_xpath('//*[@id="bloq_interior"]/div/div/div/ul/li[3]/ul/li[2]/a')
#imports.click()
#
##Selecting data display options and country
#
#time.sleep(3)
#
#valor=driver.find_element_by_xpath('//*[@id="tdSelect1"]/select/option[1]')
#valor.click()
#time.sleep(1)
#pais=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[1]/tbody/tr/td[3]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[1]/div/input')
#pais.send_keys('Alemania')
#select=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[1]/tbody/tr/td[3]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[1]/div/img[2]')
#select.click()
#time.sleep(1)
#tiempo=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[2]/tbody/tr/td[1]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[2]/div/img[1]')
#tiempo.click()
#time.sleep(1)
#ver=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[3]/tbody/tr[3]/td[2]/a/span')
#ver.click()
#time.sleep(1)
#
##Rotate table so all the data can be scrapped
#
#rotar=driver.find_element_by_xpath('//*[@id="seleccionModal"]/img')
#rotar.click()
#time.sleep(1)
#A=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[2]/fieldset/table/tbody/tr[2]/td/select/option[2]')
#A.click()
#time.sleep(1)
#B=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[3]/fieldset/table/tbody/tr[2]/td/img[1]')
#B.click()
#time.sleep(1)
#C=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[4]/fieldset/table/tbody/tr[2]/td/select/option[1]')
#C.click()
#time.sleep(1)
#D=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[3]/fieldset/table/tbody/tr[2]/td/img[3]')
#D.click()
#time.sleep(1)
#E=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/div/a/span')
#E.click()
#time.sleep(1)
#
#figures = [e.text for e in driver.find_elements_by_class_name('dataCell')]
#del figures[0]
#timetags = [e.text for e in driver.find_elements_by_class_name('tableCellMed')]
#
##print(country)
#df_base = pd.DataFrame(list(zip(timetags, figures)),
#columns =['Time', 'Alemania'])
#
#############
##Loop for the other countries
#############
#
#Countries_exc_ger = ['Reino Unido', 'Países Bajos', 'Irlanda', 'Suecia', 'Dinamarca', 'Bélgica', 'Italia', 'Francia', 'Suiza', 'Chequia', 'Polonia']
#Countries_exc_ger_eng = ['United Kingdom', 'The Netherlands', 'Ireland', 'Sweden', 'Denmark', 'Belgium', 'Italy', 'France', 'Switzerland', 'Czechia', 'Poland']
##countires' names in the list are in Spanish as is the language of the source webpage
#counter = 0
#
#for i in Countries_exc_ger:
#    print(f'Progress {((counter + 1)/12)*100}%')'
#    print(f'Working on {Countries_exc_ger_eng[counter]}....')
#    counter += 1
#
#    url = 'http://www.gobiernodecanarias.org/istac/jaxi-istac/menu.do?uripub=urn:uuid:a19805e5-1674-4efd-b047-1ab0abac9c36'
#    driver.get(url)
#
#    #Getting data on imports
#
#    time.sleep(3)
#
#    imports=driver.find_element_by_xpath('//*[@id="bloq_interior"]/div/div/div/ul/li[3]/ul/li[2]/a')
#    imports.click()
#
#    #Selecting data display options and country
#
#    time.sleep(3)
#
#    valor=driver.find_element_by_xpath('//*[@id="tdSelect1"]/select/option[1]')
#    valor.click()
#    time.sleep(1)
#    pais=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[1]/tbody/tr/td[3]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[1]/div/input')
#    pais.send_keys(f'{i}')
#    select=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[1]/tbody/tr/td[3]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[1]/div/img[2]')
#    select.click()
#    time.sleep(1)
#    tiempo=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[2]/tbody/tr/td[1]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[2]/div/img[1]')
#    tiempo.click()
#    time.sleep(1)
#    ver=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[3]/tbody/tr[3]/td[2]/a/span')
#    ver.click()
#    time.sleep(1)
#
#    #Rotate table so all the data can be scrapped
#
#    rotar=driver.find_element_by_xpath('//*[@id="seleccionModal"]/img')
#    rotar.click()
#    time.sleep(1)
#    A=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[2]/fieldset/table/tbody/tr[2]/td/select/option[2]')
#    A.click()
#    time.sleep(1)
#    B=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[3]/fieldset/table/tbody/tr[2]/td/img[1]')
#    B.click()
#    time.sleep(1)
#    C=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[4]/fieldset/table/tbody/tr[2]/td/select/option[1]')
#    C.click()
#    time.sleep(1)
#    D=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[3]/fieldset/table/tbody/tr[2]/td/img[3]')
#    D.click()
#    time.sleep(1)
#    E=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/div/a/span')
#    E.click()
#    time.sleep(1)
#
#    figures = [e.text for e in driver.find_elements_by_class_name('dataCell')]
#    del figures[0]
#    timetags = [e.text for e in driver.find_elements_by_class_name('tableCellMed')]
#
#    
#    df = pd.DataFrame(list(zip(timetags, figures)),
#    columns =['Time', f'{i}'])
#    df_base = df.merge(df_base, on='Time')

# Without time.sleep()

In [4]:
############
#Start (Germany)
############
url = 'http://www.gobiernodecanarias.org/istac/jaxi-istac/menu.do?uripub=urn:uuid:a19805e5-1674-4efd-b047-1ab0abac9c36'
driver.get(url)

print('Progress 0%')
print('Working on Germany....')    
#Getting data on imports


imports=driver.find_element_by_xpath('//*[@id="bloq_interior"]/div/div/div/ul/li[3]/ul/li[2]/a')
imports.click()

#Selecting data display options and country


valor=driver.find_element_by_xpath('//*[@id="tdSelect1"]/select/option[1]')
valor.click()
pais=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[1]/tbody/tr/td[3]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[1]/div/input')
pais.send_keys('Alemania')
select=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[1]/tbody/tr/td[3]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[1]/div/img[2]')
select.click()
tiempo=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[2]/tbody/tr/td[1]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[2]/div/img[1]')
tiempo.click()
ver=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[3]/tbody/tr[3]/td[2]/a/span')
ver.click()

#Rotate table so all the data can be scrapped

rotar=driver.find_element_by_xpath('//*[@id="seleccionModal"]/img')
rotar.click()
A=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[2]/fieldset/table/tbody/tr[2]/td/select/option[2]')
A.click()
B=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[3]/fieldset/table/tbody/tr[2]/td/img[1]')
B.click()
C=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[4]/fieldset/table/tbody/tr[2]/td/select/option[1]')
C.click()
D=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[3]/fieldset/table/tbody/tr[2]/td/img[3]')
D.click()
E=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/div/a/span')
E.click()

figures = [e.text for e in driver.find_elements_by_class_name('dataCell')]
del figures[0]
timetags = [e.text for e in driver.find_elements_by_class_name('tableCellMed')]

#print(country)
df_base = pd.DataFrame(list(zip(timetags, figures)),
columns =['Time', 'Alemania'])

############
#Loop for the other countries
############

Countries_exc_ger = ['Reino Unido', 'Países Bajos', 'Irlanda', 'Suecia', 'Dinamarca', 'Bélgica', 'Italia', 'Francia', 'Suiza', 'Chequia', 'Polonia']
Countries_exc_ger_eng = ['United Kingdom', 'The Netherlands', 'Ireland', 'Sweden', 'Denmark', 'Belgium', 'Italy', 'France', 'Switzerland', 'Czechia', 'Poland']
#countires' names in the list are in Spanish as is the language of the source webpage
counter = 0

for i in Countries_exc_ger:
    print(f'Progress {round(((counter + 1)/12)*100,2)}%')
    print(f'Working on {Countries_exc_ger_eng[counter]}....')
    counter += 1

    url = 'http://www.gobiernodecanarias.org/istac/jaxi-istac/menu.do?uripub=urn:uuid:a19805e5-1674-4efd-b047-1ab0abac9c36'
    driver.get(url)

    #Getting data on imports


    imports=driver.find_element_by_xpath('//*[@id="bloq_interior"]/div/div/div/ul/li[3]/ul/li[2]/a')
    imports.click()

    #Selecting data display options and country


    valor=driver.find_element_by_xpath('//*[@id="tdSelect1"]/select/option[1]')
    valor.click()
    pais=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[1]/tbody/tr/td[3]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[1]/div/input')
    pais.send_keys(f'{i}')
    select=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[1]/tbody/tr/td[3]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[1]/div/img[2]')
    select.click()
    tiempo=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[2]/tbody/tr/td[1]/fieldset/table/tbody/tr[1]/td/table/tbody/tr[3]/td[2]/div/img[1]')
    tiempo.click()
    ver=driver.find_element_by_xpath('//*[@id="tabla"]/div/div/table[3]/tbody/tr[3]/td[2]/a/span')
    ver.click()
    

    #Rotate table so all the data can be scrapped

    rotar=driver.find_element_by_xpath('//*[@id="seleccionModal"]/img')
    rotar.click()
    A=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[2]/fieldset/table/tbody/tr[2]/td/select/option[2]')
    A.click()
    B=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[3]/fieldset/table/tbody/tr[2]/td/img[1]')
    B.click()
    C=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[4]/fieldset/table/tbody/tr[2]/td/select/option[1]')
    C.click()
    D=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/table/tbody/tr/td/table/tbody/tr/td[3]/fieldset/table/tbody/tr[2]/td/img[3]')
    D.click()
    E=driver.find_element_by_xpath('//*[@id="tablaFormRotacionPost"]/div/a/span')
    E.click()

    figures = [e.text for e in driver.find_elements_by_class_name('dataCell')]
    del figures[0]
    timetags = [e.text for e in driver.find_elements_by_class_name('tableCellMed')]

    
    df = pd.DataFrame(list(zip(timetags, figures)),
    columns =['Time', f'{i}'])
    df_base = df.merge(df_base, on='Time')
    
print('Progress 100%')
print('Task accomplished')

Progress 0%
Working on Germany....
Progress 8.33%
Working on United Kingdom....
Progress 16.67%
Working on The Netherlands....
Progress 25.0%
Working on Ireland....
Progress 33.33%
Working on Sweden....
Progress 41.67%
Working on Denmark....
Progress 50.0%
Working on Belgium....
Progress 58.33%
Working on Italy....
Progress 66.67%
Working on France....
Progress 75.0%
Working on Switzerland....
Progress 83.33%
Working on Czechia....
Progress 91.67%
Working on Poland....
Progress 100%
Task accomplished

In [5]:
display(df_base)

,Time,Polonia,Chequia,Suiza,Francia,Italia,Bélgica,Dinamarca,Suecia,Irlanda,Países Bajos,Reino Unido,Alemania
0,2021 Noviembre (p),"4.473,862","4.698,110","2.220,403","31.485,825","36.338,226","6.008,680","2.178,621","1.574,086","6.561,863","36.734,327","11.720,918","29.201,971"
1,2021 Octubre (p),"3.360,605","9.997,751","1.711,822","7.672,856","12.718,099","4.617,084","2.493,726","1.773,129","3.440,667","29.173,793","6.908,026","25.644,328"
2,2021 Septiembre (p),"2.619,986","7.827,948","1.331,296","11.305,727","10.842,908","6.359,599","1.133,544","1.540,708","5.547,320","39.631,925","6.700,103","26.015,663"
3,2021 Agosto (p),"2.627,623","3.586,898","1.031,052","7.893,321","13.490,680","11.802,737","1.636,533","1.318,356","5.301,273","16.572,673","4.030,151","39.025,092"
4,2021 Julio (p),"2.102,901","10.212,904","1.264,930","7.513,558","16.195,542","10.413,309","1.557,271","1.475,441","4.772,880","18.454,604","3.430,143","35.785,879"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,2000 Mayo,"214,749","1.157,004","1.329,931","13.113,114","16.634,547","5.679,787","3.160,726","2.051,808","4.542,349","13.673,464","12.542,574","38.203,434"
280,2000 Abril,"201,830","1.178,224","1.734,597","11.175,775","20.080,934","3.712,788","2.636,032","3.174,356","2.641,005","12.448,452","14.196,394","30.831,520"
281,2000 Marzo,"1.031,405","1.988,490","1.569,511","19.485,000","15.723,292","5.777,047","3.576,811","3.623,335","4.636,274","15.648,672","18.859,595","40.891,206"
282,2000 Febrero,"226,559","1.081,681","1.417,999","14.355,147","14.780,881","4.929,076","2.452,499","3.563,718","2.430,753","12.040,646","19.267,473","29.782,221"
283,2000 Enero,"270,836","1.454,801","1.337,558","12.116,538","26.034,030","4.769,615","2.327,888","2.812,154","4.063,343","14.547,488","20.156,728","31.775,371"

In [6]:
df_base.to_csv('canary_imports_dirty.csv')